# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: contacts_db
